# sp.toml
IDPEntityID = "https://my.edu/idp/shibboleth"
IDPdepo     = "idp_depo"
EntityID    = "https://my.edu/saml/metadata"
KeyFile     = "certs/key.pem"
CertFile    = "certs/cert.pem"

AcsUrls = ["https://my.edu/saml/acs"]
SlsUrls = ["https://my.edu/saml/sls"]

[[AttributeConsumingServices]]
    [AttributeConsumingServices.Details] 
        ServiceNames = [
            { Name = "SAML Giri≈ü", Lang = "tr" },
            { Name = "SAML Login", Lang = "en" }
        ]
        Attributes = [
          "eduPersonTargetedID",
          "eduPersonScopedAffiliation",
          "eduPersonAffiliation",
          "cn",
          "sn",
          "givenName",
          "mail",
          "uid",
        ]
